# fly.toml app configuration file generated for test-api-c-uxna on 2025-01-26T18:35:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-api-c-uxna'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23.4'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
